### ISSUE TITLE
tistory oauth2 연결 중에 죽는 문제.

### ISSUE THREAD

**Issue by kimalec** [saltfactory/passport-tistory#1]
follow-redirects version이 업데이트 되면서 아래와 같이 연결오류가 발생하는 것 같습니다.

``` js
AssertionError: callback must be a function
    at parseOptions (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport-tistory/node_modules/follow-redirects/create.js:117:12)
    at Object.H.request (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport-tistory/node_modules/follow-redirects/create.js:102:22)
    at exports.OAuth2._executeRequest (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/oauth/lib/oauth2.js:132:30)
    at exports.OAuth2._request (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/oauth/lib/oauth2.js:111:8)
    at TistoryStrategy._oauth2.getOAuthAccessToken (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport-tistory/lib/passport-tistory/strategy.js:54:10)
    at TistoryStrategy.OAuth2Strategy.authenticate (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport-tistory/node_modules/passport-oauth2/lib/strategy.js:169:18)
    at attempt (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at Object.authenticate [as handle] (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at next_layer (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/route.js:107:5)
    at /var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:205:24
    at Function.proto.process_params (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:269:12)
    at next (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:199:19)
    at next (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:176:38)
    at Function.proto.handle (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:151:3)
    at Layer.router (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:24:12)
```

**Comment by adunStudio** [comment]
현재 이 라이브러리는 안되는건가요??
callback is must function 이라는 오류가뜹니다..
